### ISSUE TITLE
Searching is not working, results in JS errors

### ISSUE THREAD

**Issue by tylerwillingham** [mattfordham/Quickee#2] opened 2012-09-10 18:34 UTC
I don't get any JS errors when I open quickee but for every keystroke I enter into the input box I get a JS error.

For example if I hit "q", and in Quickee type "channel" I get 7 JS errors in the console.

http://i.imgur.com/6E5C9.png

**Comment by mattfordham** [comment] 2012-09-10 18:36
Thanks for the report. That looks like Chrome... am I right?

**Comment by tylerwillingham** [comment] 2012-09-10 18:43
You're correct!

Additionally this site is using a modified version of FocusLab's mutli-env config. This shouldn't be an issue but I figured I would throw it out there just in case it's a path-related issue.

**Comment by mattfordham** [comment] 2012-09-10 23:11
Hey there. I just re-tested in Chrome and with a couple different EE installs and couldn't reproduce. Could you give me some more specifics of your install? Any other add-ons? Chrome and OS version? EE version? Were you able to get it working in another install of EE? Thanks!

**Comment by Kwickell** [comment] 2012-10-22 09:26
I got the same errors as @tylerwillingham, solved it by adding a small hack to the JS.
In my case Zoo flexible admins rewrite of the main nav broke the Quickee JS.

Replace line 36 in _themes/third_party/quickee/quickee.js_

``` javascript
} else if ($element.attr("title").match(reg)) {
```

with this

``` javascript
} else if (typeof $element.attr("title") !== 'undefined' && $element.attr("title").match(reg)) {
```

It got it working for me but as with any quick fix... I dont know what i might have broken in other places. :smile:

**Comment by mattfordham** [comment] 2012-10-22 16:23
Thanks for the info. I'll look into confirming your patch works ASAP. Coincidentally, I was just thinking about adding support for Zoo Flexible Admin, so hopefully this'll kill two birds with one stone. Stand by :)

**Comment by tylerwillingham** [comment] 2012-10-22 16:24
I believe I was using Zoo Flexible Admin on the site where I had this issue, too. I think we ended up disabling it because we didn't need it and I noticed that Quickee was working all of a sudden.

**Comment by mattfordham** [comment] 2012-10-22 16:26
Good to know, thanks!

**Comment by mattfordham** [comment] 2012-10-22 18:58
Just pushed a fix for this (thanks @Kwickell). Let me know if it pops up again.

**Closed as completed by mattfordham** 2012-10-22 18:58 UTC
